### ISSUE TITLE
rename domain to laravelbestpratices.com

### ISSUE THREAD

**Issue by buonzz** [laraveltherightway/laraveltherightway.github.io#18]
sub-tree of #16  -  proposal has been made by Blaxus to move the domain to laravelbestpractices.com

**Comment by buonzz** [comment]
i'm looking at the possibility of doing this, factors I consider are:
- what will happen to the laraveltherightway.com domain?
- i would need to create an entire new repo and  organization for it

**Comment by ISTPdev** [comment]
Well, normally If you rename a repo Github will automatically redirect to the new repo. That way you can keep the old Commits and rename the domain. Similarly I suggest that a similar action on the domain to forward requests. A DNS redirect would probably be the simplest solution. A quick whois tells me you're using Godaddy. They should have redirecting without hosting a site.

**Comment by assertchris** [comment]
I support this decision. :)

**Comment by buonzz** [comment]
the site is using jekyll, the way how i did it is i put an A record in my dns records to GH ip, then set a CNAME so that whenever laraveltherightway.github.io is requested, it will instead use my apex domain . either way, i'll try to figure out. i might need to merge my local branches to upstream before doing these stuffs. will let you know when i bought the domain and happen to worked on it.
really backed up right now with so many things.
thanks
