### ISSUE TITLE
Translation to Russian

### ISSUE THREAD

**Issue by vanadium23** [laraveltherightway/laraveltherightway.github.io#29]
Hello, guys.

I'm really found of sites like this and decided to make a translation to Russian. I'll be pleased if it is needed (:

You can see it with following [url](http://vanadium23.github.io/laraveltherightway.github.io/)

**Comment by buonzz** [comment]
@vanadium23  nice one buddy :-)
will have it linked to the main page soon

**Comment by buonzz** [comment]
link to Russian translation is now placed in the Translation page :)
https://github.com/laraveltherightway/laraveltherightway.github.io/commit/3554cebc1f12ae76370f63fdab3a1921cae5694d
