### ISSUE TITLE
URL "https://rebuildinglaravel.com" is wrong.

### ISSUE THREAD

**Issue by john29917958** [laraveltherightway/laraveltherightway.github.io#33]
The URLs "https://rebuildinglaravel.com/" in [_posts/03-03-01-how-it-works.md](https://github.com/laraveltherightway/laraveltherightway.github.io/blob/master/_posts/03-03-01-how-it-works.md) at line 8 and line 9 are wrong. It seems like the URL is changed to "http://rebuildinglaravel.com/" (uses http instead of https).

**Comment by john29917958** [comment]
@buonzz: Thank you for your merge! May I close this issue with a link refer to the pull-request you've merged?

**Comment by buonzz** [comment]
@john29917958  sure :+1:

**Comment by john29917958** [comment]
Please refer to #34.
