### ISSUE TITLE
update to 5.1?

### ISSUE THREAD

**Issue by williandandrade** [laraveltherightway/laraveltherightway.github.io#36]
What do you think to update external links to laravel 5.1? or create subdivisions for releases versions?

**Comment by buonzz** [comment]
hi, yeah i think there is a lot of new things as well in laravel 5.1 that is worth mentioning/including in the listing. i'll be working in my fork and merge it as soon as i had finalized it.
thank you

**Comment by buonzz** [comment]
sorry for the drag in here. I had updated several area to be sync with 5.2. But generally, we would like to have for it to be always updated with latest stable release.

there are some suggestions about having a separate section for each version,  that might be something we are looking forward in the future for sure as soon as there are many as contributors :)

**Comment by buonzz** [comment]
got this updated to 5.8
