### ISSUE TITLE
useful resources links

### ISSUE THREAD

**Issue by buonzz** [laraveltherightway/laraveltherightway.github.io#4]
do you have any website that you think could help our fellow laravel developers to learn something new?
you can add it in here
http://www.laraveltherightway.com/#other_resources

just issue a PR and i'll merge it over

**Comment by lozadaOmr** [comment]
The updated link to other resources
[http://www.laravelbestpractices.com/#other_resources](http://www.laravelbestpractices.com/#other_resources)
