### ISSUE TITLE
Suggestion: Make content more readable?

### ISSUE THREAD

**Issue by DanJFletcher** [laraveltherightway/laraveltherightway.github.io#42]
Just came across this resource now - Pretty handy reference.

Right away though, I was compelled to open the inspector and override default styles just so I could read the content.

Suggestion:

```
.site-content{
    padding: 20px 40px 40px 320px;
    font-family: sans-serif;
    max-width: 800px;
    margin: 0 auto;
    font-size: 125%;
    line-height: 135%;
}
```

**Comment by buonzz** [comment]
thank you for pointing this out, will definitely apply this soon :)

**Comment by buonzz** [comment]
it took a while.. but better late than never..
