### ISSUE TITLE
[WIP] Translation PT-BR

### ISSUE THREAD

**Issue by marabesi** [laraveltherightway/laraveltherightway.github.io#47]
Hello guys,

I've started to translate the content to PT-BR, which can be accessed at https://marabesi.github.io/laraveltherightway.github.io/.

**Comment by ghost** [comment]
hi @marabesi excuse me, but I don't know how to start the translation to Spanish, I tried to use Wikipage but it's not available.

Can you help me?

**Comment by buonzz** [comment]
Hello Guys!  :)
If you are still interested, kindly update the translation to newest version?
