### ISSUE TITLE
php artisan app:name 

### ISSUE THREAD

**Issue by axiomette** [laraveltherightway/laraveltherightway.github.io#63]
In Laravel 6.0, php artisan app:name YourNameHere was removed from artisan commands (https://github.com/laravel/framework/pull/27575)

This makes the recommended practice of renaming the App namespace redundant.

**Comment by buonzz** [comment]
thanks for the heads up! will remove that section if that is the case

**Comment by buonzz** [comment]
this is now addressed https://github.com/laraveltherightway/laraveltherightway.github.io/commit/94dc42909571ae2d1362e6ffbab9f109087821e7
