### ISSUE TITLE
Link to 'translations' wiki entry is broken in readme file

### ISSUE THREAD

**Issue by WaveHack** [laraveltherightway/laraveltherightway.github.io#69]
https://github.com/laraveltherightway/laraveltherightway.github.io/blob/c8b70b778d9f3a21870d6d4cbc644e26b4feaf9c/README.md#L49

Two issues here:

1. The repository name is misspelled ('...gitjub.io/...')
2. No wiki pages exist on this repository to begin with

What do we want to do with this?

**Comment by buonzz** [comment]
thank you for pointing this out. this is dealt with now
